#ifndef BATTLEFORHONOUR_NEUTRALOBJECTSTRATEGY_H
#define BATTLEFORHONOUR_NEUTRALOBJECTSTRATEGY_H


class NeutralObjectStrategy {

public:
    virtual int getUnitTypeMultiply()=0;
};

#endif //BATTLEFORHONOUR_NEUTRALOBJECTSTRATEGY_H
