TEMPLATE = app
CONFIG += console c++17
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        Factory/Armorfactory/armorfactory.cpp \
        Factory/Armorfactory/heavyarmorfactory.cpp \
        Factory/Armorfactory/lightarmorfactory.cpp \
        Factory/Armorfactory/mediumarmorfactory.cpp \
        Factory/Armorfactory/noarmorfactory.cpp \
        Factory/UnitFactory/dragonfactory.cpp \
        Factory/UnitFactory/goldminerfactory.cpp \
        Factory/UnitFactory/kamikadzefactory.cpp \
        Factory/UnitFactory/thieffactory.cpp \
        Factory/UnitFactory/towerfactory.cpp \
        Factory/UnitFactory/unitfactory.cpp \
        Factory/UnitFactory/warriorfactory.cpp \
        Factory/Weaponfactory/bowweaponfactory.cpp \
        Factory/Weaponfactory/magicweaponfactory.cpp \
        Factory/Weaponfactory/noweaponfactory.cpp \
        Factory/Weaponfactory/swordweaponfactory.cpp \
        Factory/Weaponfactory/weaponfactory.cpp \
        Unit/FlyingUnit/dragon.cpp \
        Unit/FlyingUnit/flyingunit.cpp \
        Unit/FlyingUnit/kamikadze.cpp \
        Unit/GroundUnit/groundunit.cpp \
        Unit/GroundUnit/thief.cpp \
        Unit/GroundUnit/warrior.cpp \
        Unit/StandingUnit/goldminer.cpp \
        Unit/StandingUnit/standingunit.cpp \
        Unit/StandingUnit/tower.cpp \
        UnitBuilder/unitbuilder.cpp \
        UnitBuilder/unitdirector.cpp \
        atributes/armor/armor.cpp \
        atributes/armor/heavyarmor.cpp \
        atributes/armor/lightarmor.cpp \
        atributes/armor/mediumarmor.cpp \
        atributes/armor/noarmor.cpp \
        atributes/weapon/bow.cpp \
        atributes/weapon/magic.cpp \
        atributes/weapon/noweapon.cpp \
        atributes/weapon/sword.cpp \
        atributes/weapon/weapon.cpp \
        field/celloffield.cpp \
        field/gamefield.cpp \
        field/iterator.cpp \
        field/point2d.cpp \
        main.cpp \
        unit/unit.cpp \

HEADERS += \
        Factory/Armorfactory/armorfactory.h \
        Factory/Armorfactory/heavyarmorfactory.h \
        Factory/Armorfactory/lightarmorfactory.h \
        Factory/Armorfactory/mediumarmorfactory.h \
        Factory/Armorfactory/noarmorfactory.h \
        Factory/UnitFactory/dragonfactory.h \
        Factory/UnitFactory/goldminerfactory.h \
        Factory/UnitFactory/kamikadzefactory.h \
        Factory/UnitFactory/thieffactory.h \
        Factory/UnitFactory/towerfactory.h \
        Factory/UnitFactory/unitfactory.h \
        Factory/UnitFactory/warriorfactory.h \
        Factory/Weaponfactory/bowweaponfactory.h \
        Factory/Weaponfactory/magicweaponfactory.h \
        Factory/Weaponfactory/noweaponfactory.h \
        Factory/Weaponfactory/swordweaponfactory.h \
        Factory/Weaponfactory/weaponfactory.h \
        Unit/FlyingUnit/dragon.h \
        Unit/FlyingUnit/flyingunit.h \
        Unit/FlyingUnit/kamikadze.h \
        Unit/GroundUnit/groundunit.h \
        Unit/GroundUnit/thief.h \
        Unit/GroundUnit/warrior.h \
        Unit/StandingUnit/goldminer.h \
        Unit/StandingUnit/standingunit.h \
        Unit/StandingUnit/tower.h \
        UnitBuilder/unitbuilder.h \
        UnitBuilder/unitdirector.h \
        atributes/armor/armor.h \
        atributes/armor/heavyarmor.h \
        atributes/armor/lightarmor.h \
        atributes/armor/mediumarmor.h \
        atributes/armor/noarmor.h \
        atributes/weapon/bow.h \
        atributes/weapon/magic.h \
        atributes/weapon/noweapon.h \
        atributes/weapon/sword.h \
        atributes/weapon/weapon.h \
        field/celloffield.h \
        field/gamefield.h \
        field/iterator.h \
        field/point2d.h \
        unit/ifarming.h \
        unit/imovable.h \
        unit/unit.h \
