
#ifndef UNTITLED13_DOUBLEPLACINGONFIELDEXCEPTION_H
#define UNTITLED13_DOUBLEPLACINGONFIELDEXCEPTION_H
#include <exception>

class DoublePlacingOnFieldException: std::exception {

};

#endif //UNTITLED13_DOUBLEPLACINGONFIELDEXCEPTION_H
